### ISSUE TITLE
Cannot add batch labels with py2neo 1.6.4

### ISSUE THREAD

**Issue by Alan-R** [nigelsmall/py2neo#383]
I'm adding code to add labels to the nodes I create.  All the updates I perform are through batch operations.  When I try this, I get an "__Unsupported URI scheme *None*__" error.

Here's the code I'm running:
    ```print >> sys.stderr, 'ADDING LABELS for', type(node), cls.__meta_labels__()
    self.batch.add_labels(node, *cls.__meta_labels__())```

[I tried the code with and without the * -- it makes no difference]

```cls.__meta_labels__()``` returns an array/list of strings (one in the case below):

The results of running it are below:
```
USING PYTHON VERSION 2.7.8 (default, Oct 20 2014, 15:05:19)
[GCC 4.9.1]
USING NEO4J VERSION (2, 1, 3, u'')
USING py2neo VERSION 1.6.4
ADDING LABELS for <class 'py2neo.neo4j.Node'> *['Class_CMAclass']*
cma.tests.store_test TestCreateOps.test_drone ... error: cma.tests.store_test TestCreateOps.test_drone
Traceback (most recent call last):
  File "./cma/tests/store_test.py", line 210, in test_drone
    store = initstore()
  File "./cma/tests/store_test.py", line 202, in initstore
    CMAinit(None)
  File "cma/cmainit.py", line 95, in __init__
    CMAdb.store.commit()
  File "cma/store.py", line 967, in commit
    self._batch_construct_add_labels()          # Not sure what these return
  File "cma/store.py", line 830, in _batch_construct_add_labels
    self.batch.add_labels(node, *cls.__meta_labels__())
  File "/usr/local/lib/python2.7/dist-packages/py2neo/neo4j.py", line 2923, in add_labels
    uri = self._uri_for(node, "labels")
  File "/usr/local/lib/python2.7/dist-packages/py2neo/neo4j.py", line 2615, in _uri_for
    offset = len(resource.service_root.graph_db.__uri__)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/neo4j.py", line 462, in graph_db
    return GraphDatabaseService.get_instance(self.__metadata__["data"])
  File "/usr/local/lib/python2.7/dist-packages/py2neo/neo4j.py", line 338, in __metadata__
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/neo4j.py", line 360, in refresh
    self._metadata = ResourceMetadata(self._get().content)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/neo4j.py", line 365, in _get
    product=self._product)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 803, in get
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 388, in submit
    http, rs = submit(self.method, uri, self.body, headers)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/httpstream/http.py", line 264, in submit
    raise ValueError("Unsupported URI scheme " + repr(uri.scheme))
ValueError: Unsupported URI scheme None
```

**Comment by nigelsmall** [comment]
Hard to tell exactly but I'm wondering if `node` is an abstract rather than concrete node instance? A node will need to be concrete for the `add_labels` method.

**Comment by Alan-R** [comment]
It's only interesting for abstract nodes.  I never need to add labels
after the node is created.  I know all the labels I need to apply, and I
know the content.  I just wanna create the node...

You mean I need to make two transactions to create one node?  That
doesn't sound very transactional ;-).  I really need transactions to be
transactional...

Sounds like this is a bug.

**Comment by nigelsmall** [comment]
The REST API don't expose a method to create a node *with* labels so there's no way for py2neo to support it, at least outside of Cypher. The only possible way to do this is to use a Cypher `CREATE` query.

**Comment by Alan-R** [comment]
Can I create these nodes in a batch job then refer to the nodes created
by a Cypher CREATE query relatively, so I can also create relationships
between these nodes?

If this is the case, I can switch to using Cypher CREATE queries.

So, two things:
    Can I do a Cypher CREATE in a batch job?
    Can I create relationships between nodes created by Cypher CREATEs
in the same batch job?

Or do I just need to create a single massive Cypher CREATE for
everything in my transaction and screw all the batch job stuff?

**Comment by nigelsmall** [comment]
Cypher and batches don't play well together. That is: you can execute Cypher within a batch but you can't refer to the values returned using the batch cross-reference mechanism. So the answers to your questions are "yes" and "no" respectively.

The intended way to carry out this kind of work is now through Cypher transactions. As I know you're working with 1.6, I'll point you at the relevant docs:

http://nigelsmall.com/py2neo/1.6/cypher/#id2

Transactions here are a little basic compared to those in 2.0 but should be fully functional. You can probably just create the nodes and relationships you need in a single Cypher statement.

**Comment by Alan-R** [comment]
Thanks for the help!  It's much appreciated!

**Comment by nigelsmall** [comment]
By the way, if something is missing in the 1.6 transaction classes that exists in the 2.0 classes, I'm happy to look at backporting.
