### ISSUE TITLE
Dynamic Exception class creation prevents normal catch behaviour

### ISSUE THREAD

**Issue by jonathantelfer** [nigelsmall/py2neo#384]
In error.py the GraphError class dynamically creates exception subclasses using the type() function, e.g. EntityNotFoundException when pull() is called on a non-existent node.

These classes cannot be referenced on an except statement as they are never assigned to a name, i.e. this fails due to EntityNotFoundException not existing as a class reference:

```python
try:
    ...
except py2neo.error.EntityNotFoundException as e:
    ...
```
This means that users of py2neo have to catch the generic GraphError exception, interrogate it to determine whether to handle it and re-raise it if not. This not only prevents the normal practice of only catching exceptions we're interested in, it also leads to fragile client code as any changes in Neo4j exceptions are passed along to py2neo clients without warning.

py2neo should define its own set of exceptions and map incoming Neo4j exceptions to them rather than creating types dynamically.

**Comment by nigelsmall** [comment]
Py2neo does have a large set of client side exceptions for calls to the transactional Cypher endpoint but, you're right, this does not exist for other parts of the library. For the parts of the REST API that aren't `/transaction/`, the docs do not provide full details of error messages that may be returned, hence the decision to generate exceptions dynamically.

If you have the time to determine from the Neo4j source code the full set of error messages that exist in the other parts of the API and raise a PR to implement something more static, I'd be happy to review.
