### ISSUE TITLE
Neobox fails

### ISSUE THREAD

**Issue by mjmare** [nigelsmall/py2neo#386]
Running neobox fails:
  venv/bin/neobox install my-box community 2.1.6
gives this error:
  global name 'FileExistsError' is not defined

Same with version N4J 2.2.0-M02
Running python 2.7.9 with py2neo 2.0.3

Thanks!

**Comment by nigelsmall** [comment]
Confirmed as a bug. This is looking for an error that only exists in Python 3.

**Comment by nigelsmall** [comment]
Addressed in https://github.com/nigelsmall/py2neo/commit/abaf79680f60d3fa4806cb1332ba11d692a417cc. Will be released in 2.0.4.

**Comment by mjmare** [comment]
Hi Nigel

This error has gone away in v2.0.4 but neither neobox nor neoget download anything. They report 403 Forbidden.
I've tried:
venv/bin/neoget community 2.1.5
venv/bin/neoget community 2.2.0-M03
venv/bin/neobox install devbox community 2.2.0-M03

**Comment by nigelsmall** [comment]
`403 Forbidden` is generally returned when the server version is no longer available for download from `dist.neo4j.org`. I suggest trying a cURL directly to the underlying URL to confirm that you get the same result.

**Comment by mjmare** [comment]
The problem is that dist.neo4j.org redirects to http://neo4j.com/download/ where one selects the community version which links to something like  http://info.neo4j.com/download-thanks.html?edition=community&flavour=unix&release=2.2.1 The page seems to use some javascript to do the download from <something>/artifact.php?name=neo4j-community-2.2.1-unix.tar.gz (I maybe wrong here)

**Comment by mjmare** [comment]
Bug is still there for py2neo 2.0.7 and neo4j 2.2.2
