### ISSUE TITLE
Extracting results of cypher queries

### ISSUE THREAD

**Issue by ptchankue** [nigelsmall/py2neo#390]
Hi there!
I am sorry if this issue is a duplicate.

I am using py2neo to get data from neo4j
''' python
graph_db = neo4j.GraphDatabaseService() # 
query = neo4j.CypherQuery(graph_db, "START n=node(*) RETURN n ")
for record in query.stream():
	    print record[0]
I would like to extract the result of record[0] in a dictionary so as to get properties easily. For example record[0]["name"] gives me the the value of the property name, I would like to check if it exists prior to read it. Since it is not a dictionary, has_key doesn't work.
Can you guide me on this issue?

Regards,
Patrick

**Comment by nigelsmall** [comment]
Hi Patrick

You don't state which version of py2neo your're using but in py2neo 2.0, `Node.properties` are an instance of `PropertySet` which itself inherits from `dict`. To that end, you can use any standard `dict` operation on `Node.properties`. For example:

```python
if "name" in node.properties:
    name = node.properties["name"]
```

Or even more succinctly:

```python
if "name" in node.properties:
    name = node["name"]
```

Hope this helps
Nigel

**Comment by ptchankue** [comment]
Hi Nigel,

Thank you for the speedy response. I am using py2neo version 1.6.4, I will
update it and see what I can get from the latest version.

Regards,
Patrick

**Comment by nigelsmall** [comment]
For the upgrade, you might find this article useful:

http://nigelsmall.com/py2neo/2.0-unleashed

It covers most of the major changes between the two versions.

**Comment by ptchankue** [comment]
Hi Nigel, 
Thanks a million. I have upgraded and everything seems to be working fine.  
:)
Regards,
Patrick
