### ISSUE TITLE
Known bug in WeakValueDictionary's setdefault() causes issues in Node,Rel and Relationship caches in multithreaded environments 

### ISSUE THREAD

**Issue by fallonchen** [nigelsmall/py2neo#391]
WeakValueDictionary.setdefault() and WeakValueDictionary.pop() will sometimes return None in multithreaded environments, as explained here http://bugs.python.org/issue19542. The patch is pending review.

I've been able to reproduce the problem by running the test case x.py that's linked in the bug report using both python 2.7.9 and python 3.4.3. 

I have also encountered the problem during development of a Flask app that uses py2neo. This app is run on Apache using mod_wsgi-express (prefork, 1 process, 5 threads). 

Anyhow, since Node.cache, Rel.cache, and Relationship.cache all inherit from WeakValueDictionary and have methods that call setdefault(), I've been seeing NoneType errors in my Flask app. 

For instance, this snippet in Rel#hydrate() in core.py:
 ``` 
        if inst is None:
            new_inst = cls()
            new_inst.__stale.update({"properties"})
            inst = cls.cache.setdefault(self, new_inst)

        cls.cache[self] = inst
```
Will intermittently produce:
```
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/core.py", line 912, in match
    for result in results:
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/cypher/core.py", line 453, in next
    return self.__next__()
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/cypher/core.py", line 450, in __next__
    return next(self.__response_item)
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/cypher/core.py", line 443, in __response_iterator
    yield producer.produce(self.graph.hydrate(assembled(record_data)))
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/core.py", line 839, in hydrate
    return type(data)(map(self.hydrate, data))
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/core.py", line 806, in hydrate
    return Relationship.hydrate(data)
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/core.py", line 2421, in hydrate
    Rel.hydrate(data),
    File "/Users/fallonchen/.virtualenvs/ul06/lib/python2.7/site-packages/py2neo/core.py", line 1769, in hydrate
    cls.cache[self] = inst
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 103, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
    File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 267, in __new__
    self = ref.__new__(type, ob, callback)
    TypeError: cannot create weak reference to 'NoneType' object

```

I've found that you can get around the problem by replacing setdefault() with:

            if self not in cls.cache:
                 cls.cache[self] = new_inst
             inst = cls.cache[self]

Is this a good approach? I haven't looked too deeply into whether or not pop() is called, but I assume that it would also have to be patched.

**Comment by nigelsmall** [comment]
Thanks for pointing this out, I hadn't come across it before. Do you happen to have any simple code that demonstrates the issue (I realise that for a multithreaded application/intermittent problem this might be unlikely!)

**Comment by fallonchen** [comment]
Hmmm, this seems to work: 
```
import threading
import py2neo
import random
from py2neo import Graph, Node, Relationship

def worker(graph):
	"""
		target function for thread
		generates an edge between two somewhat randomly selected test nodes
	"""
	nodes = list(graph.find('test'))
	source = random.choice(nodes[:len(nodes)/2])
	target = random.choice(nodes[len(nodes)/2 + 1:])


	relationship = Relationship(source, 'TEST_CONNECT', target)
	graph.create(relationship)

def populate(graph):
	"""
		called once to populate graph with test nodes 
	"""
	for i in range(10):
		n = Node('test')
		graph.create(n)

	nodes = list(graph.find('test'))

	# need to create the edges in the main thread in order
	# to generate the error; not sure why
	for i in range(3):
		source = random.choice(nodes[:len(nodes) /2])
		target = random.choice(nodes[len(nodes)/2 + 1:])	
		r = Relationship(source, 'TEST_CONNECT', target)
		graph.create(r)

def generate_bug():
	graph = Graph()
	graph.delete_all()
	populate(graph)

	thread_pool = []
	for thread_id in range(3):
		t = threading.Thread(name=thread_id, target=worker, args=(graph,)) 
		t.start()
		thread_pool.append(t)

	for thread in thread_pool:
		t.join() 


	for r in graph.match(None,'TEST_CONNECT', None):
		print r

if __name__ == '__main__':
	generate_bug()
```

I ran this using python 2.7.9. You may have to run the script more than once before the bug appears, but it is coming up pretty consistently for me. Thanks for taking a look!

**Comment by nigelsmall** [comment]
Excellent stuff, that's really useful! I'm not sure when I'll get time to address the issue due to a high workload right now, but I'll make sure a fix or a workaround is included for 2.0.6.

**Comment by anaximander** [comment]
I ran into the same issue today.  Thanks @nigelsmall and @fallonchen for taking a look into it and coming up with a fix!  Looking forward to 2.0.6.

**Comment by nigelsmall** [comment]
This should now be fixed (or more accurately, worked around!) It would be great if either @fallonchen or @anaximander could verify by installing latest code from `release/2.0.6` branch.

**Comment by anaximander** [comment]
I switched to 2.0.6 and so far so good.  In my case, it was happening intermittently, but typically frequently enough that I would have seen it by now.  I'll comment again if I see it, but until then: thank you!

**Comment by grucin** [comment]
I'm not sure is it related, but in multithreaded environments this script print scary error message:

    $ python weakref_bug.py 
    Exception KeyError: (u'http://localhost:7474/db/data/relationship/7246',) in <function remove at 0x19358c0> ignored
    Exception KeyError: (u'http://localhost:7474/db/data/relationship/7247',) in <function remove at 0x19358c0> ignored
    Exception KeyError: (u'http://localhost:7474/db/data/relationship/7248',) in <function remove at 0x19358c0> ignored

I have the same error in my flask app.

**Comment by adityaSomak** [comment]
Hi @nigelsmall,
 I have the same error as @grucin. Its probably connected. I am trying to work with ConceptNet data and load into Neo4j GraphDB.  I am using multi-threading and relationships are created using Graph().create(..).
```
Exception KeyError: (u'http://localhost:7474/db/data/relationship/1',) in <function remove at 0x7f4e0f2392a8> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/2',) in <function remove at 0x7f4e0f2392a8> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/3',) in <function remove at 0x7f4e0f4c8a28> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/4',) in <function remove at 0x7f4e0f4c8848> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/5',) in <function remove at 0x7f4e0f4c8cf8> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/6',) in <function remove at 0x7f4e0f235758> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/7',) in <function remove at 0x7f4e0f239488> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/8',) in <function remove at 0x7f4e0f239488> ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/9',) in <function remove at 0x7f4e0f235cf8> ignored
```

**Comment by khafan246** [comment]
same error in multi thread environment, using latest v3

**Comment by horejsek** [comment]
I see this error with Flask in dev mode, no multi threaded env, with latest py2neo==3. I think it could be related to this issue, but I am not sure. Always happen when I do some change and Flask wants to reload app. Without automatic reload it looks fine.

    Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x2b983807b9d8>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/weakref.py", line 108, in remove
        del self.data[wr.key]
    KeyError: ('http://localhost:7474/db/data/node/138',)

**Comment by foxxyz** [comment]
Seconding @horejsek. Also receiving this error using Flask with Python 3.5.1 and py2neo 3, lots of these upon reloading the app in dev mode:

```
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x102fa2378>
Traceback (most recent call last):
  File "/Users/ijanssen/Virtualenvs/amog3/lib/python3.5/weakref.py", line 114, in remove
    del self.data[wr.key]
KeyError: ('http://localhost:7474/db/data/node/1857',)
```

**Comment by fmder** [comment]
I had this error with neo4j 2.3.3, but now that I upgraded to 3.0.3 the warning is gone.

**Comment by horejsek** [comment]
I upgraded to py2neo 3.1.1 (using Python 3.5.0 on Debian Wheezy) and still see this error.

**Comment by foxxyz** [comment]
To add to my comment above, besides in development, I'm also seeing this in production on Ubuntu 16.04 using Python 3.5.1 and py2neo 3.1.1 using gunicorn and gevent to serve the app.

**Comment by fmder** [comment]
Sorry I upgraded my Neo4j version to 3.0.3 not py2neo

**Comment by bonej079** [comment]
I too upgraded py2neo and am still getting the error.

**Comment by bsquire0128** [comment]
I am getting the same error without using multithreading, I am simply making nodes from a dictionary object and it intermittly gives very similar out put as above 

Exception KeyError: (u'http://localhost:7474/db/data/node/52260',) in <function remove at 0x11aa7fb18> ignored
Exception KeyError: (u'http://localhost:7474/db/data/node/52261',) in <function remove at 0x11aa7fb18> ignored

**Comment by sebaacuna** [comment]
Also seeing this error on OSX (El Capitan) with py2neo 3.1.1 and neo4j 3.0.3

**Comment by MaxwellPayne** [comment]
I am running Flask with a [gevent](https://pypi.python.org/pypi/gevent) server, and every time I stopped the server by a keyboard interrupt I got a big dump of `Exception KeyError: (u'http://localhost:6464/db/data/node/371992',) in <function remove at 0x1047f2de8> ignored` going to the stderr. I figured this was related to the way gevent handles context, so I decided to replace py2neo's `ThreadLocalWeakValueDictionary` caches with `weakref.WeakValueDictionary` instances. I configure my Flask app like so:

```python
import weakref
import flask, py2neo

app = flask.Flask(__name__)

@app.before_first_request
def before_first_request():
    py2neo.Node.cache = weakref.WeakValueDictionary()
    py2neo.Relationship.cache = weakref.WeakValueDictionary()
```

This hack avoids the error messages, but could have unintended consequences I haven't yet encountered. I would like to find a more elegant solution given that Flask servers are always going to multithread somehow.

**Comment by piyush121** [comment]
Still seeing this error. We are using following libraries :
gunicorn (19.6.0)
py2neo (3.1.1)
Flask (0.11.1)
Running with Python 3.5.1 and neo4j 3.1.

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/fetch_flask/lib/python3.5/weakref.py", line 114, in remove
    del self.data[wr.key]
KeyError: 'http://107.170.154.179:7474/db/data/node/35504'
```

**Comment by nigelsmall** [comment]
Does anyone here have a snippet of code that can be used as a test case to recreate this issue?

**Comment by nigelsmall** [comment]
If you have seen this bug, please install 3.1.2 (released a few minutes ago) and retest. Thank you!

**Comment by piyush121** [comment]
I will test it and get back to you ASAP. I was seeing this bug every time i run my application. let's see if it comes again.

**Comment by piyush121** [comment]
It works good for me. I think you can close this bug now. Thanks a lot for that fix 👍

**Comment by nigelsmall** [comment]
Closing this issue then.

**Comment by ij-ami** [comment]
@nigelsmall Seconding the successful fix. Thank you for all your fantastic efforts in developing this library!

**Comment by foxxyz** [comment]
@nigelsmall Seconding the successful fix. Thank you for all your fantastic efforts in developing this library!
