### ISSUE TITLE
IPython kernel crash on import

### ISSUE THREAD

**Issue by erwindassen** [nigelsmall/py2neo#397]
Hi there,

Since moving from py2neo 1.6 to 2.0 I am having problems running it from the IPython (console *and* notebook). The IPython kernel dies everytime i try to import py2neo with 

`import py2neo`

I've installed 2.0.6 following instructions: `pip install py2neo` and I'm running in windows 7 with the Anaconda python 3.4 64-bit distribution.

Note that I can sucessfully import and run scripts if I use the python interpreter directly. Can anyone confirm this?

**Comment by nigelsmall** [comment]
I can support on Linux using CPython 2.7, 3.3 and 3.4 but I don't develop or test py2neo on Windows and am not familiar with Anaconda so probably can't offer much help.

Do you get an error message or log entry?

**Comment by erwindassen** [comment]
I will try on a mac later today and will update this post.

I do not get any error message/log except for the setence: 
"It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console."

**Comment by erwindassen** [comment]
I've tried py2neo 2.0.7 on my mac running neo4j 2.2.1 CE and Anaconda python 3.4 64-bit and it runs without problem inside IPython Notebook (and console). So this seems to be isolated to Windows. If I find a workaround I'll update this.
