### ISSUE TITLE
Can't get py2neo to work?

### ISSUE THREAD

**Issue by scheung38** [nigelsmall/py2neo#402]
In my sampleTest python project where installed py2neo:

```python
$neo4j start
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
Starting Neo4j Server...WARNING: not changing user
process [19863]... waiting for server to be ready...... OK.
http://localhost:7474/ is ready.

from py2neo import Graph
```

I get back:
```python
from: can't read /var/mail/py2neo
```

**Comment by nigelsmall** [comment]
Are you running `from py2neo import Graph` directly from the shell? It needs to be run from within a Python console or application.

**Comment by scheung38** [comment]
Tried both within anaconda virtual environment as well as within pycharm

**Comment by nigelsmall** [comment]
As stated in the docs, I cannot support non-standard Python interpreters so I don't know why anaconda might fail. With regard to pycharm, you'll need to make sure your project is using the correct interpreter within the settings.

Note that the only error message you have supplied is one which will be generated from trying to run directly within a bash shell.

**Comment by scheung38** [comment]
Anaconda is only pre-packaging some of the most popular Python libraries around so users don't have to install them from scratch. Python is still the python 2.7.9 that you would get if downloading from python.org

**Comment by svidela** [comment]
Hi,

I'm using py2neo within Anaconda without any issue so far:

```
$ ipython
Python 2.7.9 |Continuum Analytics, Inc.| (default, Mar  9 2015, 16:20:48)
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from py2neo import Graph
In [2]: graph = Graph()
In [3]:
```

Regards,

**Comment by nigelsmall** [comment]
Please provide more information or close the issue.

**Comment by fitzgeraldsteele** [comment]
@svidela Did you install py2neo with conda or pip?
