### ISSUE TITLE
OGM request: provide more control when saving/loading objects 

### ISSUE THREAD

**Issue by mjmare** [nigelsmall/py2neo#417]
The OGM would be more useful if some hook would be provided so that the user has more control on how objects are saved and loaded. 

Example use case: I'd like to save an object and have the object's class name as a label. Since the store.save will only store the object's attrs as node properties I have to resort to 1) save object 2) reload object 3) set object.__node__.labels. 4) save object again. Yuck.

PS1 the store.save method seems to use a deprecated function set_properties.
PS2 it seems that passing a newly created node (see use case above; I wanted to pass the label) as a kwarg in the store.save(obj, node=mynewnode) does not work. I get a 500 server error. Did not explore further.

**Comment by nigelsmall** [comment]
OGM was written pre-2.0, before labels. It remains in place largely for legacy reasons. I plan to replace it with a more modern variant when time allows :-)

**Comment by nigelsmall** [comment]
(accidentally clicked close button previously)

**Comment by mjmare** [comment]
Looking forward to it! A 'real' OGM is sorely missing IMHO. 
I'd be happy to test.

**Comment by mjmare** [comment]
BTW What are your thoughts on NeoModel, since it's based on Py2Neo?

**Comment by nigelsmall** [comment]
I approve it wholeheartedly. Not least as I helped @robinedwards with its design :-)

**Comment by mjmare** [comment]
Good to know! But you are still considering writing a new OGM at some point in the future. What shortcomings do you see in NeoModel then, or is it just because you can? ;-)

Met vriendelijke groet,

Marcel Maré

**Comment by nigelsmall** [comment]
I am, as and when time allows. Neomodel is designed using a Django-esque philosophy and so is necessarily constrained by the expectations of a traditional table-based ORM. My plans involve something more graph-specific without those constraints.

**Comment by robinedwards** [comment]
I'd argue the contrary here, I tried to design it to be graph specific just people tend to use it with Django. The motivation for building it was that the other major OGM at the time neo4django tried to hide the graph behind an API that matched the Django's ORM (for integration purposes). I wanted to avoid this.

I've made the API directly match the actions used in graphs however I am sure this could be taken a lot further than I have. Perhaps some of the semantics in neomodel are similar to those of popular table based ORMs which make it easier to pick up for people coming from that background.

**Comment by nigelsmall** [comment]
:+1: didn't intend to imply such familiarity was a bad thing :-)

**Comment by robinedwards** [comment]
haha of course not :-)

**Comment by robinedwards** [comment]
It's great having the integration between the two projects, I am hoping to be able to use both at my work in the near future :-)

**Comment by nigelsmall** [comment]
Awesome - what's the use case?
