### ISSUE TITLE
rfc3986.URI.build() classmethod ignores certain changes in arguments when invoked more than once?

### ISSUE THREAD

**Issue by lebedov** [nigelsmall/py2neo#421]
The second invocation of URI.build() below returns the same URI as the first invocation even when it is passed a different `user_info` value. Is this expected? I'm using py2neo 2.0.7.

```
from py2neo.packages.httpstream.packages.urimagic import URI

scheme = 'http'
host = 'localhost'
port = 7474
absolute_path_reference = '/db/data'
user_info = 'foo:bar'
u = URI.build(scheme=scheme, host=host, port=port,
              absolute_path_reference=absolute_path_reference,
              user_info=user_info)
print u
user_info = 'qux:mux'
u = URI.build(scheme=scheme, host=host, port=port,
              absolute_path_reference=absolute_path_reference,
              user_info=user_info)
print u
```

**Comment by lebedov** [comment]
httpstream 1.3.0 doesn't appear to have this problem.

**Comment by nigelsmall** [comment]
This sounds incorrect and possibly a bug. But I'm curious why you're using this class directly as this is not part of py2neo's documented API.

**Comment by lebedov** [comment]
I'm using httpstream to assemble the URI used to access a Cypher database in an [extension](https://github.com/lebedov/icypher) I wrote to access Neo4J from within IPython using py2neo.

**Comment by nigelsmall** [comment]
Cool.

I'm not sure why this would fail in py2neo but not in httpstream. As far as I recall, both should have the same code although my memory may have failed and one may be out of date. Either way, this definitely appears to be a bug and I'll work on a fix. Thanks for raising :-)

**Comment by lebedov** [comment]
Thanks for the library :-)

**Comment by nigelsmall** [comment]
Moved to https://github.com/nigelsmall/urimagic/issues/4
