### ISSUE TITLE
Graph authorization: set_auth_token not available and NEO4J_AUTH_TOKEN not used.

### ISSUE THREAD

**Issue by flekschas** [nigelsmall/py2neo#422]
I am trying to set a basic authorization header for connecting to Neo4J but `set_auth_token` is not available and setting the environmental variable `NEO4J_AUTH_TOKEN` doesn't do anything. I am always getting the same `py2neo.error.Unauthorized: http://localhost:7474/db/data/` error.

```
>>> import py2neo
>>> py2neo.set_auth_token()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'set_auth_token'
```

I've [searched the repo](https://github.com/nigelsmall/py2neo/search?utf8=%E2%9C%93&q=set_auth_token) for the source of that the `set_auth_token` method but haven't found anything other than [this comment](https://github.com/nigelsmall/py2neo/blob/3bc0049aad26172ca62108fa553950fd42102b3f/py2neo/core.py#L563-L567). Searching for `NEO4J_AUTH_TOKEN` yields exactly the same result.

Am I missing something or is this method simply gone? If its gone how can I properly authorize?

**Comment by nigelsmall** [comment]
The `set_auth_token` method existed for a brief period of time but when the underlying auth mechanism changed, it was removed.

See [here](http://py2neo.org/2.0/essentials.html#authentication) for the docs on how to do auth.

**Comment by flekschas** [comment]
I figured out that [`neo2py.authenticate`](https://github.com/nigelsmall/py2neo/blob/3bc0049aad26172ca62108fa553950fd42102b3f/py2neo/core.py#L83-L107) can be used. I assume the documentation is just outdated?

**Comment by flekschas** [comment]
Okay thanks. Maybe the its better to remove the related paragraph from the [docs](http://py2neo.org/2.0/essentials.html#the-graph) as it's a little confusing.

**Comment by nigelsmall** [comment]
Ah OK, hadn't realised that was still there. Thanks for spotting!
