### ISSUE TITLE
cached node properties bug

### ISSUE THREAD

**Issue by RedCraig** [nigelsmall/py2neo#427]
I have an issue where I create a node, via a `MERGE` statement, and set one of it's properties to `True`.
I read the node and it's properties with py2neo, and test that property is `True`. All good.

I then run a similar MERGE statement, as the node already exists it gets updated via `ON MATCH SET` clause and the `True` property is set to `False`.
I read the node and it's properties with py2neo again, but that property is still `True`, it should be `False`.

I double checked the nodes property with `neo4j-shell`, and the web UI too. Both show the node as having that property set to `False`, py2neo is incorrectly reporting it's value.

I think the issue is here:
https://github.com/nigelsmall/py2neo/blob/cc9aa3e80720fe99abe194dc5ce09a73b2a93cef/py2neo/core.py#L1431
The newly read properties are updated with the previously read & cached properties.

It should probably update the cached properties with the newly read ones:
```python
inst.properties.update(properties)
```
In which case these two lines are no longer required:
```python
properties.update(inst.properties)
inst._PropertyContainer__properties.replace(properties)
```

I wanted to make sure that the change wouldn't subtly break things by using py2neo unittests, but unfortunately I'm having an issue running them with a fresh checkout - see #426.

**Comment by singit** [comment]
I'm facing this issue right now, did it work by your update?

**Comment by RedCraig** [comment]
@singit Yes I've been using the updated version locally and without issue for the last month. 
I've just created pull request #431 with the fix.

**Comment by singit** [comment]
@RedCraig Thanks a lot : )

**Comment by foxxyz** [comment]
Just ran into this as well... almost pulled my hair out before finding this. Excellent fix @RedCraig !

@nigelsmall Will you be able to include this in 2.0.8?

**Comment by nigelsmall** [comment]
If there's a bug here then I'm happy to apply a fix but `update` is not the same as `replace` as the latter completely replaces the full set of properties whereas the former is applied on top.

Either way, I would first like to see a standalone piece of code that would demonstrate the actual issue so that this can be used within a unit test.

**Comment by RedCraig** [comment]
I'll see about adding a unittest.

The bug isn't to do with `replace`, it's the order the update is applied [here](https://github.com/nigelsmall/py2neo/blob/cc9aa3e80720fe99abe194dc5ce09a73b2a93cef/py2neo/core.py#L1431):
`properties.update(inst.properties)`
i.e. update & overwrite the new properties with the old ones.
