### ISSUE TITLE
Cypher Transaction stream() documentation insufficient

### ISSUE THREAD

**Issue by Alan-R** [nigelsmall/py2neo#432]
OK. I see it returns a RecordStream. Unfortunately it doesn't document what's _in_ the RecordStream :-(

**What's fields are in the Records in the RecordStream?**

**Will I get one Record per transaction element?** _I suspect that's true, but you should say._

**What do those Records look like for various kinds of Cypher queries?** _node creation, deletion, updates, adding/removing labels, etc_.

**When I add a node where do I find the newly-created Node object?** _do I have to do a separate query - and where do I find the results in that query?_

**When I add a relationship, where do I find the newly-created Relationship object?**  _do I have to do a separate query - and where do I find the results in that query?_

    Thanks!

    -- Alan

**Comment by nigelsmall** [comment]
The output from a Cypher query in py2neo is consistent with that from all other Neo4j surfaces. The output is dictated by the Cypher `RETURN` clause, as documented here:

http://neo4j.com/docs/stable/query-return.html

**Comment by Alan-R** [comment]
So, to be clear, when I create 100 new nodes with 200 relationships, then I need to have a really, really long RETURN statement where everything is named consistently with something that I can figure out later?

**Comment by nigelsmall** [comment]
Yes. Well, you could do it that way but more sensible would be to build up a Cypher transaction consisting of 100 or 200 separate CREATE/RETURN statements, each with distinct parameters.
