### ISSUE TITLE
Cypher SET doesn't work (or something wrong in my usage?)

### ISSUE THREAD

**Issue by hyunjun** [nigelsmall/py2neo#438]
Hi, my very simple code doesn't work properly. The result of my code is difference from neo4j browser.
```
from py2neo import Graph

remote_graph = Graph('http://x.y.z.w:7474/db/data')
remote_graph.cypher.execute('MATCH (n:Test_Neo4j_Node) DELETE n')
remote_graph.cypher.execute("CREATE (n:Test_Neo4j_Node {name: 'test0', count: 0, num_list: [0, 1, 2, 3], str_list: ['a', 'b', 'c', 'd']})")
records = remote_graph.cypher.execute('MATCH (n:Test_Neo4j_Node) RETURN n')
for record in records:
  print record[0]._id, record[0]['name'], record[0]['count'], record[0]['num_list'], record[0]['str_list']

remote_graph.cypher.execute("MATCH (n:Test_Neo4j_Node {name: 'test0'}) SET n.count = n.count + 10, n.num_list = [0, 100, 2, 3], n.str_list = ['a', 'x', 'y']")
records = remote_graph.cypher.execute('MATCH (n:Test_Neo4j_Node) RETURN n')
for record in records:
  print record[0]._id, record[0]['name'], record[0]['count'], record[0]['num_list'], record[0]['str_list']
```
Just created one node then update properties. The result is like below;
```
$ python test.py
1177781 test0 0 [0, 1, 2, 3] [u'a', u'b', u'c', u'd']
1177781 test0 0 [0, 1, 2, 3] [u'a', u'b', u'c', u'd']
```
Nothing changed. However, neo4j browser shows like below;
![2015-09-23 11 18 31](https://cloud.githubusercontent.com/assets/248764/10036653/4090b910-61e5-11e5-93cb-1b6051965da9.png)
Properties are updated. Something wrong in my code?
Versions; neo4j 2.2.3, python 2.7.10, py2neo 2.0.7
Thanks,
Jun

**Comment by nigelsmall** [comment]
Py2neo does not introspect Cypher statements to find out what actions are taking place and therefore has no way to know that it's local copy of the remote node needs to be updated. You will need to execute an explicit `pull` on the node to copy the changes from server to client.
