### ISSUE TITLE
Errors on create_unique showing in stdout

### ISSUE THREAD

**Issue by npem** [nigelsmall/py2neo#450]
Hi,

In my code I call:
x = graph.create_unique(Relationship(pkg_node, rel_type, node))

The edge is always created, but I also get errors printed to standard error that are unexpected and that I cannot trap.

Here is sample output:
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018836' start=u'node/449829' end=u'node/449830' type=u'contains' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018837' start=u'node/449830' end=u'node/449165' type=u'Characterized_By' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018838' start=u'node/449830' end=u'node/449167' type=u'Created' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018839' start=u'node/449830' end=u'node/449799' type=u'Used' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018840' start=u'node/449830' end=u'node/449801' type=u'Characterized_By' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018841' start=u'node/449830' end=u'node/449828' type=u'Connected_To' properties={}

Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018836',) in function remove at 0x7f659c2a7b18 ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018837',) in function remove at 0x7f659c2a7b18 ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018838',) in function remove at 0x7f659c2a7b18 ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018839',) in function remove at 0x7f659c2a7b18 ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018840',) in function remove at 0x7f659c2a7b18 ignored
Exception KeyError: (u'http://localhost:7474/db/data/relationship/1018841',) in function remove at 0x7f659c2a7b18 ignored

Can you shed any light on this issue, or tell me where to look?

Thanks

**Comment by npem** [comment]
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018836' start=u'node/449829' end=u'node/449830' type=u'contains' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018837' start=u'node/449830' end=u'node/449165' type=u'Characterized_By' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018838' start=u'node/449830' end=u'node/449167' type=u'Created' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018839' start=u'node/449830' end=u'node/449799' type=u'Used' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018840' start=u'node/449830' end=u'node/449801' type=u'Characterized_By' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018841' start=u'node/449830' end=u'node/449828' type=u'Connected_To' properties={}>,)


Trying again for the first 6 lines of output

**Comment by npem** [comment]
"(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018836' start=u'node/449829' end=u'node/449830' type=u'contains' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018837' start=u'node/449830' end=u'node/449165' type=u'Characterized_By' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018838' start=u'node/449830' end=u'node/449167' type=u'Created' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018839' start=u'node/449830' end=u'node/449799' type=u'Used' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018840' start=u'node/449830' end=u'node/449801' type=u'Characterized_By' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018841' start=u'node/449830' end=u'node/449828' type=u'Connected_To' properties={}>,)
"

**Comment by npem** [comment]
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018836' start=u'node/449829' end=u'node/449830' type=u'contains' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018837' start=u'node/449830' end=u'node/449165' type=u'Characterized_By' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018838' start=u'node/449830' end=u'node/449167' type=u'Created' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018839' start=u'node/449830' end=u'node/449799' type=u'Used' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018840' start=u'node/449830' end=u'node/449801' type=u'Characterized_By' properties={}>,)
(<Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018841' start=u'node/449830' end=u'node/449828' type=u'Connected_To' properties={}>,)

**Comment by npem** [comment]
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018836' start=u'node/449829' end=u'node/449830' type=u'contains' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018837' start=u'node/449830' end=u'node/449165' type=u'Characterized_By' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018838' start=u'node/449830' end=u'node/449167' type=u'Created' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018839' start=u'node/449830' end=u'node/449799' type=u'Used' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018840' start=u'node/449830' end=u'node/449801' type=u'Characterized_By' properties={}
Relationship graph=u'http://localhost:7474/db/data/' ref=u'relationship/1018841' start=u'node/449830' end=u'node/449828' type=u'Connected_To' properties={}

**Comment by nigelsmall** [comment]
These messages should not go to stdout. Which version of the library are you using?

**Comment by npem** [comment]
My mistake -- they are going to standard error. Version is 2.0.7

**Comment by npem** [comment]
I am still concerned about the output, even though I had misstated where the messages are going.
