### ISSUE TITLE
How do I disable/control py2neo caching?

### ISSUE THREAD

**Issue by tonyennis** [nigelsmall/py2neo#458]
I have a situation where one process is changing a node. Another process using py2neo is reading that node. However, this process seems to have cached the node and won't return the new values. Is pull() the solution? is there a way to control the caching?

http://stackoverflow.com/questions/34273072/is-py2neo-caching-burning-me

**Comment by nigelsmall** [comment]
There's no explicit way to control the cache but you can clear it using `Node.cache.clear()`.
