### ISSUE TITLE
Formatting query results as a pandas.DataFrame

### ISSUE THREAD

**Issue by dhimmel** [nigelsmall/py2neo#468]
I generally want my query results as a dataframe. I use the following command to convert a `py2neo.cypher.core.RecordList` to a pandas.DataFrame`

```python
results = neo.cypher.execute(query)
pandas.DataFrame(results.records, columns = results.columns)
```

Would it make sense to add a `to_pandas()` method to `RecordList`? If not, the workaround is easy enough.

**Comment by brifordwylie** [comment]
+1 on query results as a pandas dataframe :)

**Comment by keturn** [comment]
Hmm, I can see the appeal of this, but I wouldn't want to see pandas become a requirement of py2neo.

How weird would it be to have a method on RecordList that only worked if pandas is installed?

**Comment by dhimmel** [comment]
> How weird would it be to have a method on RecordList that only worked if pandas is installed?

I personally think this is a great option and not weird, but I'm no expert on packaging.

I believe the [`extras_require` dependency declaration](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) is designed for this method.

**Comment by nigelsmall** [comment]
I will not be adding this. Partly because I am not familiar with that library and partly because py2neo has no dependencies by design.

I would be willing however to add a code snippet to the docs to show how this can be done.

**Comment by dhimmel** [comment]
> I will not be adding this.

Okay, I will close the issue. I do think a line in the docs on how to convert to a  `RecordList` to a `pandas.DataFrame` would be helpful. Something along the lines of my [first comment](#issue-132581876).

> I am not familiar with that library

[Pandas](http://pandas.pydata.org/) is the dataframe package for Python. Dataframes are a data structure for tabular data, such as the "Rows" output of a Cypher query. Pandas is a tier three package in [VanderPlas's Scientific Python Stack](https://speakerdeck.com/jakevdp/the-state-of-the-stack-scipy-2015-keynote?slide=7 "The State of the Stack (SciPy 2015 Keynote)") .

**Comment by dhimmel** [comment]
With py2neo v3, the [previous method](#issue-132581876) for converting Cypher query output to a `pandas.DataFrame` has changed. The following works for me in v3:

```python
cursor = neo.run(query)
records = list(cursor)
result_df = pandas.DataFrame(records, columns=records[0].keys())
cursor.close()
```

**Comment by svidela** [comment]
I'm doing this with python 3.5.1, py2neo v3, and pandas 0.18, and the following works fine for me:

```
cursor = graph.run(query)
df = pandas.DataFrame.from_records(cursor, columns=cursor.keys())
```
