### ISSUE TITLE
How can "Map literals returned over the Neo4j REST interface are ambiguous and may be hydrated as graph objects" be solved?

### ISSUE THREAD

**Issue by ExplodingCabbage** [nigelsmall/py2neo#471]
I just got the `"Map literals returned over the Neo4j REST interface are ambiguous and may be hydrated as graph objects"` warning for the first time and am wondering what can be done to solve it at the py2neo level. It's certainly an inconvenience for some Cypher syntax to be essentially broken with py2neo.

My first thought was to have py2neo parse the query and determine the expected return type for every expression, but apart from being horrifically complicated and likely to break forwards-compatibility, this is also impossible; a perverse query like this:

```
MATCH (n) RETURN CASE WHEN RAND() > 0.5 THEN n ELSE {foo: 'bar'} END LIMIT 1
```

has a non-deterministic return type.

Perhaps as an alternative `execute()` could take a `map_aliases` parameter that specifies a list of aliases from the returned records that contain maps and should not be hydrated? This would allow a usage like:

```
cypher.execute(
    'MATCH n RETURN {foo: n.foo, bar: n.bar} as part_of_n',
    map_aliases=['part_of_n']
)
```

to silence the warning.

**Comment by keturn** [comment]
I ran in to this the other day. Maybe when Neo4j 3.0 comes out we'll all switch to the new protocol that doesn't use JSON and this problem will go away?

(I haven't actually tried Neo4j 3.0 yet and I don't know anything about py2neo's support for Bolt, I'm only speculating here.)

**Comment by nigelsmall** [comment]
The warning exists as the JSON responses from the REST interface are inherently ambiguous. There is no way for py2neo (or any other client) to be able to tell what is a literal map and what is an object such as a Node.

IIRC there is some support in the standard library for suppressing warnings which may help.

With regard to Neo4j 3.0 and Bolt, this will not be a problem, as @keturn suggests. The next version of py2neo (currently v3 beta 1) supports the new protocol.

**Comment by nigelsmall** [comment]
Closing as nothing to fix.
