### ISSUE TITLE
Deadlock in multiprocess setup

### ISSUE THREAD

**Issue by khafan246** [nigelsmall/py2neo#474]
Hello
I'm trying to use latest v3 (with nep4j server v3.0.M4) in a multiprocess setup (with concurrent.futures)
in worker process, first i begin a transaction, doing some operations (create_unique, merge) and finally committing the transaction.
but i get this error every time:
```
py2neo.status.transaction.DeadlockDetected: LockClient[144] can't wait on resource RWLock[INDEX_ENTRY(613762531902278711), hash=316112251] since => LockClient[144] <-[:HELD_BY]- RWLock[NODE(741), hash=1408182123] <-[:WAITING_FOR]- LockClient[145] <-[:HELD_BY]- RWLock[INDEX_ENTRY(613762531902278711), hash=316112251]
```
at first, i was thinking that transaction commit is where the Deadlock occurs, but protecting the commit in a multiprocessing Lock context did not help.

**Comment by khafan246** [comment]
I tried many solutions with no luck.
the main problem is that transaction objects is not pickleable, making it improper for passing between processes.

**Comment by nigelsmall** [comment]
As mentioned in #348, multiprocessing isn't supported with py2neo.

**Comment by nigelsmall** [comment]
Closing as not supported
