### ISSUE TITLE
Don't like the fact py2neo is an org

### ISSUE THREAD

**Issue by laeg** [nigelsmall/py2neo#476]
You're disgraceful

**Comment by laeg** [comment]
Closing this issue as you're not worth my time Nige

**Comment by nigelsmall** [comment]
Arsehat.

**Comment by laeg** [comment]
Either enter or close this...

**Comment by nigelsmall** [comment]
I've fixed your issue. Please see here for details:
http://bit.ly/IqT6zt

**Comment by laeg** [comment]
Reopening with this face...

![image](https://cloud.githubusercontent.com/assets/5677186/13282907/26835164-dae3-11e5-8310-806148c0377e.png)

**Comment by nigelsmall** [comment]
Responding with this face...
![luke-tash](https://cloud.githubusercontent.com/assets/275311/13282972/760a68da-dae3-11e5-9d05-62d1d3e92808.jpg)

**Comment by laeg** [comment]
I moustache you a question, regarding py2neo...

**Comment by nigelsmall** [comment]
Stop using my software. You're not qualified.
