### ISSUE TITLE
making py2neo asyncio friendly

### ISSUE THREAD

**Issue by khafan246** [nigelsmall/py2neo#478]
it may be as simple as altering ```socket.recv``` with asyncio's ```reader.read``` in connection
and the benefits is obvious :+1:

**Comment by nigelsmall** [comment]
I'm not familiar with asyncio so I am unsure what "friendly" refers to here.

**Comment by nigelsmall** [comment]
Closing. Please reopen if you have more information.

**Comment by ramnes** [comment]
@technige I'm seeing that you implemented an async driver in `neo4j` ([here](https://github.com/neo4j/neo4j-python-driver/pull/299) for the curious ones). Did you consider making it used by `py2neo`? That might be worth reopening this issue either way.
