### ISSUE TITLE
Bolt Transactions Hang, works with HTTP Transactions (v3B1)

### ISSUE THREAD

**Issue by saoirse-ronan** [nigelsmall/py2neo#484]
Large merge() Bolt transactions are hanging indefinitely with py2neo 3B1.   We're using 'transaction.merge(node,label,key,value)' in batches of 1000 via graph.begin().   After several commits, the script hangs indefinitely @ transaction.commit().   The script sometimes completes with merge() but its rare and it always works if we use transaction.create().   It works flawlessly if we disable the Bolt transaction class and use the HTTP transaction instead.

**Comment by saoirse-ronan** [comment]
We disabled the Bolt transaction class and use the HTTP transaction instead and now our merge() transactions are working without hanging.  If a patch is applied to fix the Bolt connection hanging, We'll try the script again with Bolt and let you know if it works.

**Comment by nigelsmall** [comment]
This is part of the Bolt driver so moving this issue to https://github.com/neo4j/neo4j-python-driver/issues/47 and closing here.
