### ISSUE TITLE
store.save_unique("People", "email", alice.email, alice) fails in v3b1

### ISSUE THREAD

**Issue by djhenderson** [nigelsmall/py2neo#488]
I am using Python 3.5.1 on Windows 7 accessing a database on graphenedb.com. I have the free Hobby version, at the moment, with the movies database loaded.

I installed py2neo v.3b1, and successfully worked through the chapter 1 examples (and some of Chapter 2) in the py2neo handbook. I then tried working through the py2neo.ext.ogm – Object-Graph Mapping example. I ended up with this failure:

    >>> store = Store(graph)
    >>> alice = Person("alice@example.com", "Alice", 34)
    >>> store.save_unique("People", "email", alice.email, alice)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Program Files\Python 3.5\lib\site-packages\py2neo\ext\ogm\store.py", line 261, in save_unique
        self.save(subj, node)
      File "C:\Program Files\Python 3.5\lib\site-packages\py2neo\ext\ogm\store.py", line 221, in save
       self.graph.cypher.execute("MATCH (a) WHERE id(a)={a} MATCH (a)-[r]->(b) DELETE r",
    AttributeError: 'Graph' object has no attribute 'cypher'

This error, along with comments elsewhere in the handbook suggest that the failing code may not have been upgraded to use Graph.Run() to execute cypher code.

My apologies if this is fixed in v.3b2. Installing 3b2 failed

    python -m pip install py2neo==3b2
    <snip>
    No matching distribution found for py2neo==3b2

**Comment by nigelsmall** [comment]
Yes, this definitely looks like a bug and something I've missed with tests. Thanks for raising.

**Comment by nigelsmall** [comment]
Please note though that this module is likely to change significantly before final release since it is still based on legacy indexing.

**Comment by djhenderson** [comment]
Nigel,

I will watch out for that. I visited that section because I have used
several different ORMs for Python and other languages, and wanted to see
how an OGM looked and worked. I will try it out again when it is finished.

Thanks,
Doug

On 7 April 2016 at 13:21, Nigel Small <notifications@github.com> wrote:

> Please note though that this module is likely to change significantly
> before final release since it is still based on legacy indexing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nigelsmall/py2neo/issues/488#issuecomment-207056313>
>



-- 
Doug Henderson, Calgary, Alberta, Canada

**Comment by nigelsmall** [comment]
FWIW I have some partially completed designs for a replacement OGM that will draw inspiration from both Django and SQLAlchemy. If time permits, this will be included in the final v3 release. Watch this space :)
