### ISSUE TITLE
What are best practices when iterating over all nodes?

### ISSUE THREAD

**Issue by saoirse-ronan** [nigelsmall/py2neo#490]
With py2neo 3b1, we can iterate over all nodes like this:

    cursor=graph.run("MATCH (n) RETURN n")
    for n in cursor:
        print(n)

This is memory prohibitive when our node collection is over several million nodes.  What are the best practices for iterating over millions of nodes?  We can add SKIP and LIMIT to our MATCH statement.  That works, but is it the recommended solution?  A prior recommendation was to use graph.cypher.stream(), but stream() is not available in py2neo 3b1.

**Comment by nigelsmall** [comment]
Please explain why you think this is a memory issue.

**Comment by saoirse-ronan** [comment]
Using SKIP / LIMIT where LIMIT is 1, our script uses 5MB as defined by the sum of getsizeof() of all objects.  With a limit of 100, its 10MB.  With a limit of 10,000 nodes, its 96MB.  With a limit of 100,000 nodes, our script consumes 500MB.  We speculate that the script becomes memory prohibitive if we try to cursor over all 25 million nodes without utilizing SKIP / LIMIT.    Is this the expected behaviour?  We're fine with using SKIP / LIMIT but was curious if there was a better method such as a streaming interface.

**Comment by nigelsmall** [comment]
The result of a `graph.run` call does stream so an explicit `stream` method is no longer necessary. In the general case, fetching one million records should use no more memory than fetching one record. However, this depends to some extent on the surrounding application; I see three possibilities as to why you might see this behaviour:

1. You are not using the result immediately. If you make a Cypher call without fully consuming the result of a previous Cypher call (within the same transaction) the Bolt driver will buffer the results from the first call.
2. Something else in your application is using the memory. What do you do with the results you retrieve? Presumably not `print` them.
3. There may be a bug somewhere that I haven't yet found. If you can reduce this to a small test case, I can explore further.

**Comment by saoirse-ronan** [comment]
Knowing that graph.run() streams is quite helpful.  We now know that we can expect a fixed amount of memory resources regardless of the number of nodes returned by the Cypher query.   With that in mind, we tracked down our mistake.  As we iterate over the nodes, we create a transaction to create new entity nodes and relationships.  Unfortunately the number of transactions were tied to MATCH limit so as the limit increased so did the size of the transactions.  Apologies for not seeing this bug sooner.
