### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'cypher'

### ISSUE THREAD

**Issue by stevenagy** [nigelsmall/py2neo#491]
I am trying to implement the sample Py2neo code provided here: http://neo4j.com/developer/ (under PYTHON). I haven't been able to remedy the following error:

**AttributeError: 'Graph' object has no attribute 'cypher'**

Any ideas?

**Comment by nigelsmall** [comment]
The code on that page refers to the latest full release of py2neo, which is version 2. The error you see is likely to be caused by you using v3, which has not yet been released.

**Comment by jlminel** [comment]
Well, but this is the version we get on the official site :
http://neo4j.com/download-thanks/?edition=community&flavour=winstall64&release=3.0.1&_ga=1.37666595.2034706319.1463126430
so how can I get version 2 ?

**Comment by ADTC** [comment]
If you installed py2neo 3 using pip, you can change to 2.0.8 using:
```
pip uninstall py2neo
pip install py2neo==2.0.8
```
If it shows the following, you got it right:
```
Collecting py2neo==2.0.8
  Downloading py2neo-2.0.8.tar.gz (251kB)
    100% |################################| 253kB 409kB/s
Installing collected packages: py2neo
  Running setup.py install for py2neo
Successfully installed py2neo-2.0.8
```

**Comment by tsaoman** [comment]
If for some reason you need two version of py2neo, you can always use [virtualenv](https://virtualenv.pypa.io/en/stable/).
