### ISSUE TITLE
How to execute a cypher query in v3?

### ISSUE THREAD

**Issue by Zigur** [nigelsmall/py2neo#492]
I have been using py2neo v2 for a couple of weeks and now I was wondering whether to use version 2 or 3 for a project we have just started.

My issue is: how can I execute the cypher query and store the result in v3, now that the "cypher" property has been removed from the graph.
I was trying to replicate a behaviour such as:

    from py2neo import Graph
    graph = Graph()
    results = graph.cypher.execute("MATCH (n:Person) RETURN n")

My goal is to build a JSON-based REST API to retrieve data from a Neo4j database

**Comment by nigelsmall** [comment]
You will need `Graph.run` or `Transaction.run`:

http://py2neo.org/v3/database.html#py2neo.database.Graph.run
