### ISSUE TITLE
False BindError

### ISSUE THREAD

**Issue by ianseyer** [nigelsmall/py2neo#495]
Hi there.

I have a large (7m+) graph instance.

I am now attempting to iterate through them and create relationships between them. However, I am running into an issue.

I am reading the relational data from a PostGres DB instance of entities called "Articles"

```
def create_relationships():
    for entry in session.query(Article).yield_per(100):
        #iterate through all entries again, and build a relationship between parent and relations
        parent = graph.find_one("Article", "title", entry.title.lower())
        print parent['title']
        for relation in json.loads(entry.relations):
            try:
                child = graph.find_one("Article", "title", urllib.unquote(relation).lower().encode('utf-8'))
                #be sure to use the unique restraint
                if parent and child:
                    print parent.bound, child.bound
                    print parent.resource, child.resource
                    if Relationship(parent, "LINKS", child).exists():
                        print "Relationship already exists!"
                    else:
                        graph.create_unique(
                            Relationship(
                                parent,
                                "LINKS",
                                child
                            )
                        )
                else:
                    print "Relating article not found"
            except Exception as e:
                print e
                print "Unable to create relationship between", entry.title, "and", relation
                print sys.exc_info()[0]
        # count+=1
        # print count,"/",wiki_count
```

both bound and resource are True and non-null (on both parent and child), however I can not seem to create the relationship between two nodes with the following error:

`BindError: Local entity is not bound to a remote entity`

**Interesting: removing the check if Relationship().exists fixes the error.**

**Comment by nigelsmall** [comment]
`Relationship.exists` tests the existence of the remote relationship to which a local `Relationship` object is bound. In your case, that can never be true as you are creating a local object and never binding it.

I think what you actually want here is a `graph.match_one` check instead.
