### ISSUE TITLE
Update Properties in a Transaction

### ISSUE THREAD

**Issue by saoirse-ronan** [nigelsmall/py2neo#496]
With py2neo v3, Transaction is recommended over ext.batman.  With batch.set_property(), we can update node properties.  How can we update properties with Transaction?  That is, we have property X in node A.  We want to retain X and add property Y to the node.  We know `node = graph.find_one() / node['Y'] = '1' / graph.push(node)` works but for efficiency we prefer to update with Transaction.

**Comment by nigelsmall** [comment]
You should use Cypher for this and execute through `Transaction.run`.
