### ISSUE TITLE
Graph settings

### ISSUE THREAD

**Issue by saoirse-ronan** [nigelsmall/py2neo#500]
We have two problems with py2neo v3b2 and the graph settings.  This works:

```
graphURI="http://neo4j:myPassword@localhost:7474/db/data/"
self.graph=Graph(graphURI)
```

if we set use_bolt to False in py2neo/database/__init__.py.  Our script hangs with Bolt transactions, but works great with HTTP transactions.  If we do not modify  __init__.py, and instead use this setting:

```
self.graph=Graph(graphURI, bolt = False)
```

The script fails with `py2neo.packages.httpstream.http.ClientError: 401 Unauthorized`.  It also fails if we set the URI to 'http://neo4j:myPassword@localhost:7474/db/data/?bolt=False'.

Next, if we use a remote host with these settings:

```
graphURI="http://remote.domain.org:7474/db/data/"
self.graph=Graph(graphURI, user = 'neo4j', password = 'myPassword')
```

The connection is unexpectedly made to localhost rather than to the remote host.

Are we not using the proper Graph() parameters or is this a bug?

**Comment by nigelsmall** [comment]
This is a bug (I found it myself recently) and it will be fixed in the next release (beta 3 or final, I haven't decided yet).

**Comment by dchaplinsky** [comment]
@nigelsmall does screenshot below related somehow to the bug you've mentioned?

![populatedb 2016-05-01 3 -57-36](https://cloud.githubusercontent.com/assets/131186/14941902/7a662db8-0fb5-11e6-9b98-896f49cbda02.png)
