### ISSUE TITLE
Dependency Missing

### ISSUE THREAD

**Issue by AntoineHus** [nigelsmall/py2neo#501]
Hello, 
When I tried to use py2neo with gremlin the dependency is mssing. 

 File "/usr/local/lib/python2.7/dist-packages/joern-0.1-py2.7.egg/joern/all.py", line 2, in <module>
    from py2neo.ext.gremlin import Gremlin
ImportError: No module named gremlin

**Comment by nigelsmall** [comment]
Which version of py2neo are you using? The Gremlin module has been removed in v3.

**Comment by lucysimko** [comment]
I'm having the same issue -- happy to give more info. 
How do I find out what version of py2neo I'm using? (I tried py2neo -v and -version; neither worked). 
I'm using Python2.7 and Neo4J 2.1.8.
