### ISSUE TITLE
Deleting a relationship also deletes its start_node and end_node

### ISSUE THREAD

**Issue by dusktreader** [nigelsmall/py2neo#508]
Because a Relationship is a Subgraph, calling delete on it will delete it's start_node and end_node

Example:
```python
        node1 = py2neo.Node('TestNode')
        gdb.graph.create(node1)
        node2 = py2neo.Node('TestNode')
        gdb.graph.create(node2)
        print("Nodes before relationship delete")
        [print(m) for m in gdb.graph.find('TestNode')]
        rel = py2neo.Relationship(node1, node2)
        gdb.graph.create(rel)
        gdb.graph.delete(rel)
        print("Nodes after relationship delete")
        [print(m) for m in gdb.graph.find('TestNode')]
        return
```

output:
```
Nodes before relationship delete
(f7aa8e9:TestNode)
(fe115f3:TestNode)
Nodes after relationship delete
```

**Comment by nigelsmall** [comment]
As mentioned in the PR, this behaviour is by design. The `separate` method will only delete relationships if that's what you need.

http://py2neo.org/v3/database.html#py2neo.database.Transaction.separate

**Comment by dusktreader** [comment]
@nigelsmall ok, I verified that the separate method worked as you described. I thought the separate method was essentially a method to unbind a subgraph from its remote counterpart; I'm glad to learn that the delete relationships only functionality is already supported in a more seamless way.

**Comment by karzler** [comment]
@nigelsmall @dusktreader I assume separate is v3 specific. For v2, if we want to remove just the relationship, while the nodes are still intact in the graph, is there an alternative?

As of now, I tried deleting a relationship instance (`rel.delete()`, where rel is a Relationship instance), which didn't work. Alternatively, I tried deleting the relationship with `graph.delete(rel)`. Nothing worked out.

**Comment by nigelsmall** [comment]
You'll need to use Cypher to do this in v2. For example:
```
graph.cypher.execute("MATCH ()-[r]->() WHERE id(r) = {x} DELETE r", x=rel_id)
```

**Comment by karzler** [comment]
@nigelsmall Thanks, but I'll landing up with another error then. I am not sure about it though.


```
query = '''
            MATCH ()-[r:UPVOTED]->()
            WHERE ID(r) = {x}
            DELETE r
            '''
            graph.cypher.execute(query, x=rel_id)
```

This results in the error:
.... /lib/python2.7/site-packages/py2neo/cypher/error/core.py", line 54, in hydrate
    error_cls = getattr(error_module, title)
AttributeError: 'module' object has no attribute 'TypeError'

I checked for existing relationships with the following query:
 ```
query = '''
        MATCH ()-[r:LIKED]->()
        RETURN ID(r)
        '''
        print (graph.cypher.execute(query))
```
This prints the following:
    | ID(r)
---+-------
 1 |     8
 2 |     9
 3 |    10

Am I missing something?
