### ISSUE TITLE
v3 Upgrade Guide

### ISSUE THREAD

**Issue by midnightlynx** [nigelsmall/py2neo#515]
I'm noticing API changes between v2 and v3.
When developers are trying to upgrade, they'll need to know what things have been removed/relocated/renamed/replaced, what things take different arguments, and what things have different behavior.
(For instance, one 'gotcha' I found that wouldn't have been immediately obvious is that in 2.x, setting a key in a node's `.properties` attribute sets that property on (the cached version of) the node. While in v3, `.properties` returns a copy of the properties, cast to a dict, so setting keys there or using `.properties.update()` doesn't set the properties on the node itself.) 

Could you document somewhere what the user-facing changes are, so we can see what needs fixed and not either have to deeply inspect the library or wonder if we're missing something?

**Comment by nigelsmall** [comment]
As you note, some of the API have changed between v2 and v3. The docs for v3 should be complete though.

An upgrade guide is unfortunately not something that I have time to do right now. Should anyone else have time, I'm happy to edit it and include it in the docs though.

**Comment by nigelsmall** [comment]
Closing for now. Happy to reopen if someone has time to contribute this.
