### ISSUE TITLE
How to get results from a transaction ? 

### ISSUE THREAD

**Issue by imenelk** [nigelsmall/py2neo#516]
Hi,
I'm a bit confused with the new version of py2neo. I used to use transactions to send several cypher queries at a time and get all the results at once in a RecordList, but it seems to be impossible now as tx.commit() does not return anything anymore. 
Here is a sample of my code : 
tx = graph.begin()
for i,c in cases:
        param = {"case": str(c)}
        tx.run("MATCH (c:Case {caseId: {case}}) RETURN c.prop1, c.prop2", param)
results = tx.commit()
results used to contain a RecordList but now it's a None.
Could you tell me how I can access the results of the transaction with the new version ? 
Thanks,
Imen

**Comment by nigelsmall** [comment]
In v3, `tx.run` returns a `Cursor` object which can be used for navigating the Cypher results. Py2neo will automatically submit the statement to the server when the cursor is accessed.

Apologies for the poor documentation here. This wasn't updated correctly between v2 and v3. I've now made a change to describe this behaviour, which will appear following the next release.

**Comment by imenelk** [comment]
Hi,
Ok, thanks for updating the documentation. 
Best,
Imen
