### ISSUE TITLE
Subclassing py2neo.Node

### ISSUE THREAD

**Issue by TwoBitAlchemist** [nigelsmall/py2neo#529]
I'm struggling to find the correct or expected way to subclass py2neo.Node in any meaningful way.

Most py2neo methods will return Node (or related objects), but there is no way that I see to get them to return a specified class, such as a subclass. Thus, to get an instance of the subclass from a fetched node, you must convert. It's easy enough to copy the properties (`my_node = MyNode(**fetched_node)`), but then `my_node` is unbound and cannot be used with methods like `graph.match_one`.

As a workaround, I have found that I can also copy the `__remote__` property but I have a feeling this might not be the best way. For a fuller write-up on this and a reproducible example, see my [recent StackOverflow question](https://stackoverflow.com/questions/37838823/subclassing-py2neos-node-the-right-way), which unfortunately got very little attention.

As an aside, if you'd like to answer that question on StackOverflow, I'd be happy to upvote and accept whatever answer you give.

**Comment by nigelsmall** [comment]
The `Node` class is not designed for subclassing. However v3.1 (which is almost complete) will introduce the `GraphObject` class which is designed specifically for this purpose.

**Comment by nigelsmall** [comment]
http://py2neo.org/v3/ogm.html
