### ISSUE TITLE
py2neo cyper

### ISSUE THREAD

**Issue by shell4j** [nigelsmall/py2neo#530]
when i run cyper statement ,there is an error ,Invalid input '«': expected whitespace or a rel type name .
the cyper statement is "MERGE (a:Entity {name:{a}}) MERGE(b:Entity {name:{b}}) merge (a)-[:«rel»]->(b)" where rel is a variable relationship

**Comment by mmcauliffe** [comment]
The use of "«param_name»" to format cypher queries seems to have gotten removed in version 3.  To get the same functionality as before, you have to do string formatting in Python, something like:

```
"MERGE (a:Entity {{name: {{a}} }}) MERGE(b:Entity {{name: {{b}} }}) merge (a)-[:{rel}]->(b)".format(rel = "my_relationship")
```

Note the doubling up of other brackets to get python's formatting to ignore them.

**Comment by shell4j** [comment]
thanks a lot-------- 原始邮件 --------主题：Re: [nigelsmall/py2neo] py2neo cyper (#530)发件人：Michael McAuliffe 收件人：nigelsmall/py2neo 抄送：yhuang ,Author The use of "«param_name»" to format cypher queries seems to have gotten removed in version 3.  To get the same functionality as before, you have to do string formatting in Python, something like:

"MERGE (a:Entity {{name: {{a}} }}) MERGE(b:Entity {{name: {{b}} }}) merge (a)-[:{rel}]->(b)".format(rel = "my_relationship")


Note the doubling up of other brackets to get python's formatting to ignore them.

**Comment by nigelsmall** [comment]
Yes, this was an experimental feature that failed the experiment. It was too tricky to make the results consistent in all cases without building a full Cypher parser.
