### ISSUE TITLE
ImportError: No module named 'py2neo.ogm'

### ISSUE THREAD

**Issue by kracekumar** [nigelsmall/py2neo#535]
I am following this sample `https://github.com/nigelsmall/py2neo/blob/v3/demo/moviegraph/model.py`. But Python3 complains `ImportError: No module named 'py2neo.ogm'`.

#### Code

```python

from py2neo.ogm import GraphObject, Property, RelatedTo, RelatedFrom
```

Traceback

```python
ImportError                               Traceback (most recent call last)
<ipython-input-1-c74ac8dbbbda> in <module>()
----> 1 from py2neo.ogm import GraphObject, Property, RelatedTo, RelatedFrom

ImportError: No module named 'py2neo.ogm'
```

Some more info about version

```python
import py2neo
py2neo.__version__

'3'
```

```bash
krace@Kracekumars-MacBook-Pro ~> which jupyter
/Users/krace/anaconda3/bin/jupyter
krace@Kracekumars-MacBook-Pro ~> pip3 freeze | grep py2neo
py2neo==3
```

**Comment by nigelsmall** [comment]
The demo app corresponds with v3.1 of py2neo which was only released today. In general, if you're reading straight from the latest source, you'd be best off installing the bleeding edge code directly from GitHub instead of PyPI which will of course always be slightly behind.

**Comment by kracekumar** [comment]
My bad, didn't look at the branch properly. Thanks.
