### ISSUE TITLE
Let GraphObject accept kwargs to initialise object 

### ISSUE THREAD

**Issue by mjmare** [nigelsmall/py2neo#539]
It would be nice to be able to pass kwargs to initialise an object. 

Eg
```
class Person(GraphObject):
    __primarykey__ = "name"
    name = Property()
    born = Property()
    
p=Person(name='Piet, born='2012')
```

instead of:
```
p=Person()
p.name='Piet'
p.born='2012'
```

This has the additional advantage of passing a dict to the constructor:
`q=Person(**some_validated_dict)`

instead of:
```
q=Person()
for k,v in some_validated_dict:
  q[k]=v

```

**Comment by nigelsmall** [comment]
The base `GraphObject` deliberately doesn't include a default `__init__`; it's up to base classes to provide a constructor as one may not be desirable in every case.

I'd suggest that if you want this behaviour, you first subclass `GraphObject` as `ConstructableGraphObject` or something and extend your domain classes from that.

**Comment by mjmare** [comment]
I see. Just curious, why didn't you include a default __init__?

**Comment by nigelsmall** [comment]
While I can certainly see the convenience of a default constructor like this, I don't believe it's any more the job of `GraphObject` to offer this facility than it is the built-in `object` class, which doesn't offer it either.

**Comment by mjmare** [comment]
Makes sense. Thx for the clarification.
