### ISSUE TITLE
OGM: __primarykey__ not inherited?

### ISSUE THREAD

**Issue by mjmare** [nigelsmall/py2neo#541]
This may reflect my lack of comprehension of metaclasses so forgive me.

I was trying to create a base class for my GraphObject derived classes so that a uuid is auto generated and used as a primary key.

See test code below. I was surprised to find out that the value of Person.__primarykey__ is '__id__' and not 'uuid'. So, somehow, the __primarykey__ from GraphBase is not used or overridden.

```
from uuid import uuid4

class GraphBase(GraphObject):
    __primarykey__ = 'uuid'
    uuid = Property()


    def __init__(self, **kwargs):
        super().__init__()
        self.update_properties(kwargs)
        if not self.uuid:
            self.uuid = str(uuid4())

    @property
    def properties(self):
        return self.__ogm__.node.properties

    def update_properties(self, props):
        for k, v in props.items():
            setattr(self, k, v)


class Movie(GraphBase):
    title = Property()
    tag_line = Property("tagline")
    released = Property()

    actors = RelatedFrom("Person", "ACTED_IN")
    directors = RelatedFrom("Person", "DIRECTED")
    producers = RelatedFrom("Person", "PRODUCED")


class Person(GraphBase):
    name = Property()
    born = Property()

    acted_in = RelatedTo(Movie)
    directed = RelatedTo(Movie)
    produced = RelatedTo(Movie)

```

**Comment by nigelsmall** [comment]
This is a good point. I've built this with the expectation that primary labels and keys would be explicitly specified in the general case but I can see no reason why inheritance should be explicitly prevented. I'll look into making that work.
