### ISSUE TITLE
Python list as properties or merge using multiple properties

### ISSUE THREAD

**Issue by sadhana01** [nigelsmall/py2neo#546]
Hi,
I would like to know if there is a way to include python lists/arrays as properties of a node.
Neo4j supports basic arrays as properties and I want to use a list as property .
I also want to know if there is a way to merge using multiple properties since I have inserted each property as separate into a node instead of using a list.

**Comment by nigelsmall** [comment]
List properties work out of the box:
```
>>> graph.evaluate("CREATE (n) SET n.foo = {x} RETURN n.foo", x=[1, 2, 3])
[1, 2, 3]
```
