### ISSUE TITLE
How to access data from a transaction with multiple run() statements

### ISSUE THREAD

**Issue by lauralorenz** [nigelsmall/py2neo#552]
I'm trying to upgrade from py2neo 2.0.7 to 3.1.1 and am trying to work with transactions. I read the details over at https://github.com/nigelsmall/py2neo/issues/516 to learn that `tx.run()` returns a cursor object representing the underlying data stream, which I must use to access the transaction results as opposed to a `RecordList` from `tx.commit()`. 

However during my transaction, I make multiple `tx.run()` calls to accumulate statements for my transaction, and when I try to iterate through the cursor or use `cursor.data()` to collapse the entire underlying data stream it only returns data from the last `tx.run()` call. For example:

```python
graph = # a py2neo.Graph object
query = 'RETURN {data}'
parameter_list = [{"data": "hello"}, {"data": "goodbye"}]

# start the transaction
tx = graph.begin()

# iterate through the parameter list. I used to use `tx.append` here but now use `tx.run`
for parameters in parameters_list:
     # have to get access to the cursor which is returned by `tx.run`
     c = tx.run(query, parameters)

# now I expect to see two results when I ask for all of the cursor's data
print c.data()
>>> (u'{data}': u'goodbye') # but I only get the most recent :(
```

How am I supposed to access cursor so that I can get all the data from my transaction at once?

**Comment by nigelsmall** [comment]
Each time through your loop, you're assigning the cursor to the same variable. Therefore the second cursor overwrites the first.

You need something like:
```
query = 'RETURN {data}'
parameter_list = [{"data": "hello"}, {"data": "goodbye"}]
tx = graph.begin()

cursors = []  # something to collect your cursors in
for parameters in parameter_list:
    cursors.append(tx.run(query, parameters))

print(cursors[0].data())
# -> [{'{data}': 'hello'}]
print(cursors[1].data())
# -> [{'{data}': 'goodbye'}]
```

**Comment by lauralorenz** [comment]
Ah ok, I had misinterpreted the "access to the data stream" was more automagical 🔮. I haven't actually tried this yet but I will close this issue for now since that makes sense.
