### ISSUE TITLE
Suggest subgraph __bool__ method be based on existence of nodes rather than relationships

### ISSUE THREAD

**Issue by johnbodley** [nigelsmall/py2neo#554]
Given by definition for a subgraph nodes are mandatory yet relationships are optional, 

https://github.com/nigelsmall/py2neo/blob/8f83e54f3e54750b62e9f217e6f7ff3557aa9443/py2neo/types.py#L217-L220

shouldn't the `__bool__` method be based on nodes, i.e., 

    def __bool__(self):
        return bool(self.__nodes)

rather than relationships

https://github.com/nigelsmall/py2neo/blob/8f83e54f3e54750b62e9f217e6f7ff3557aa9443/py2neo/types.py#L262-L263

**Comment by nigelsmall** [comment]
The next release (WIP) contains proper checking for null subgraphs and clarifies the situation around null vs empty:

- A [null subgraph](http://mathworld.wolfram.com/NullGraph.html) (zero nodes, zero relationships) is not supported by this class, use `None` instead.
- An [empty subgraph](http://mathworld.wolfram.com/EmptyGraph.html) (one or more nodes, zero relationships) can be tested for by using `bool`.

Therefore, as you state, a valid `Subgraph` instance must contain _at least one node_.

Basing `__bool__` on relationships is consistent with `__len__` in the same class and has the effect of treating zero-length paths (for example) in the same way as Python treats zero-length strings and lists (i.e. equating to boolean False).

Also, if `__bool__` were based on nodes, it would always be `True` anyway as there can never be zero nodes!
